### ISSUE TITLE
Template Skripsi Versi 11

### ISSUE THREAD

**Issue by michaeladrian39** [ftisunpar/Skripsi#4]
Dear Pak Pascal,

Sudah ada template skripsi versi 11. Contoh: Skripsi Ariq Rahmaeri (https://github.com/arikrahma/Skripsi/tree/master/doc/DokumenSkripsi)

Best regards,

Michael Adrian (@michaeladrian39)

**Comment by pascalalfadian** [comment]
Terima kasih @michaeladrian39. Bisa bantu saya buatkan pull request? Saya tidak punya template skripsi versi 11 originalnya

**Comment by michaeladrian39** [comment]
Maaf, ternyata saya juga tidak punya template skripsi versi 11 originalnya juga

**Comment by pascalalfadian** [comment]
Fixed in 47f1adffca7bc4752a0975d8337a4e89e5210388
