### ISSUE TITLE
Versi 12 sudah ada

### ISSUE THREAD

**Issue by michaeladrian39** [ftisunpar/Skripsi#5]
cek di tinyurl.com/lionov

**Comment by pascalalfadian** [comment]
Thanks @michaeladrian39 infonya. Saya catat dulu, karena sekarang lagi cukup sibuk. Atau mungkin kamu bisa bantu saya dengan buat pull request?

**Comment by pascalalfadian** [comment]
Ditutup karena ternyata di sini sudah versi 12.
